In [1]:
print('hd')

hd


In [2]:
import numpy as np

In [7]:
    np.random.randn()

1.496556382226529

In [8]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [9]:
np.random.randint(10)

0

In [10]:
np.random.randint(554646546464)

ValueError: high is out of bounds for int32

In [11]:
np.random.randint(6313)

1166

In [12]:
np.random.randomstate(2)

AttributeError: module 'numpy.random' has no attribute 'randomstate'

In [13]:
np.array(ls
        )

NameError: name 'ls' is not defined

In [14]:
ls=(1,2,3)

In [15]:
np.array(ls)

array([1, 2, 3])

In [18]:
for i in range(1,100):
    for j in range(1,100):
        if j%2==0:
            print(np.random.randint(50))
        else:
            print(np.random.randint(50,100))
    print('\n')
            
        
        

94
46
92
46
72
22
67
15
98
26
97
37
81
24
94
7
68
38
65
7
87
13
77
10
77
30
66
19
83
7
93
36
73
6
96
11
58
34
63
13
57
26
74
45
50
20
97
5
60
5
74
5
78
11
70
41
50
48
65
29
75
20
95
32
76
8
69
24
74
6
96
18
91
48
94
0
57
38
79
21
84
26
62
38
70
18
53
15
75
35
94
39
67
38
73
29
69
7
57


61
18
87
19
77
24
80
21
61
49
56
49
87
0
86
44
98
19
77
19
88
14
86
44
57
8
54
34
78
26
52
28
61
46
89
31
60
16
74
11
60
26
72
44
50
15
66
32
89
28
71
40
84
0
63
29
56
14
50
27
65
4
89
44
91
40
66
16
89
11
75
12
78
35
75
34
88
12
59
29
54
19
81
5
69
25
78
32
63
4
84
0
64
27
82
41
63
20
93


99
17
85
47
54
22
56
35
67
20
90
9
90
42
89
44
91
28
94
2
77
38
55
46
69
18
95
30
88
48
66
20
68
15
97
39
71
44
64
0
89
3
89
39
63
23
60
3
55
2
50
32
56
49
94
11
89
2
97
0
90
21
66
17
51
24
66
39
60
17
63
49
78
25
98
32
58
44
94
17
83
7
71
42
73
47
69
11
87
38
62
21
95
39
73
33
97
39
70


52
33
70
8
61
15
98
33
91
19
85
4
90
38
50
22
55
41
58
40
98
16
84
22
52
29
81
6
70
42
54
15
88
11
69
7
56
20
55
35
59
1
70
7
78
1

44
52
49
84
45
51
44
83
33
64
8
64
0
57
30
62
46
72
38
87
43
97
35
71
12
85
16
72
25
68
17
53
17
62
40
92
33
78
17
86
13
55
34
57
5
66


53
23
67
19
51
26
51
27
76
21
72
42
75
37
93
44
60
28
59
8
51
47
83
46
99
32
91
27
57
16
61
49
90
43
52
10
56
20
64
6
96
30
57
20
53
35
55
24
93
42
98
0
58
7
88
3
51
46
69
35
89
15
71
0
92
35
90
44
80
22
78
46
82
9
52
6
55
43
94
28
88
3
97
29
62
7
81
49
89
22
69
44
59
0
82
32
82
18
60


60
18
99
40
81
12
59
46
55
13
57
7
73
4
74
14
72
23
62
11
54
36
91
26
65
40
88
33
99
41
84
44
54
15
52
10
72
34
61
49
56
35
86
25
68
25
58
22
63
6
91
45
76
33
83
47
54
33
98
33
50
39
92
48
73
27
68
11
89
3
88
0
90
39
98
43
77
39
93
1
50
13
92
4
92
16
92
13
74
15
55
30
50
13
66
37
94
5
95


89
27
99
25
59
28
98
17
94
35
87
24
70
2
62
15
76
26
69
24
78
2
75
23
90
23
95
32
53
40
87
5
96
35
73
3
81
35
76
14
80
48
51
27
67
44
56
46
75
31
56
25
61
45
58
2
87
6
80
4
78
42
72
23
93
47
52
0
79
32
70
19
60
11
50
48
76
27
95
28
93
8
76
24
64
47
53
38
78
46
96
30
60
42
90
45
86
2


91
7
58
41
65
2
61
25
94
17
58
16
80
9
58
16
76
14
91
39
81
20
70
46
71
38
91
26
71
43
95
21
80
26
82
29
89
17
96
40
60
40
54
35
81
36
53


59
32
75
17
99
38
91
11
50
12
56
5
53
34
83
7
68
34
83
33
58
39
97
31
60
47
85
41
84
7
62
2
67
38
81
41
59
27
70
15
64
16
71
31
82
47
53
46
80
41
97
15
92
33
82
7
67
44
95
9
90
32
71
39
85
5
91
13
89
10
63
2
88
30
80
20
51
37
77
14
87
9
53
24
82
11
56
4
85
35
75
47
95
6
77
2
73
30
71


53
14
96
11
68
13
51
48
52
32
99
4
68
18
82
1
64
12
65
6
53
38
87
44
88
23
83
12
64
23
71
0
60
15
68
43
79
13
72
48
86
46
50
1
81
10
67
25
87
38
62
49
58
44
87
8
96
2
62
4
95
44
74
14
81
34
89
26
91
25
96
3
74
1
98
9
89
16
81
6
81
49
81
49
99
39
76
21
57
39
76
35
97
28
84
16
82
16
73


76
25
51
7
64
47
95
35
74
48
95
19
59
42
86
49
85
31
97
39
60
41
90
34
67
44
86
49
77
6
58
1
80
49
58
2
80
35
65
2
92
14
93
33
77
17
63
39
52
43
88
21
90
2
55
7
86
13
87
7
57
0
79
25
74
4
83
3
50
28
72
48
68
12
63
12
63
42
50
6
50
22
58
11
78
32
99
7
59
13
91
14
95
37
88
2
53
10
52


8

In [19]:
ls = [x for x in range(10)]

In [20]:
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
ls = [x for x in range(10) if x%2==0]

In [33]:
ls


[0, 2, 4, 6, 8]

In [35]:
x=10
y=20
x
y

20

In [36]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
np.arange(100,2)

array([], dtype=int32)

In [38]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones(2)

array([1., 1.])

In [42]:
np.linspace(4,10,1)

array([4.])

In [43]:
ls

[0, 2, 4, 6, 8]

In [44]:
n.shape


NameError: name 'n' is not defined

In [45]:
np.shape

<function numpy.core.fromnumeric.shape(a)>

In [46]:
ls[5]=6

IndexError: list assignment index out of range

In [47]:
np.reshape(2,3)

ValueError: cannot reshape array of size 1 into shape (3,)

In [48]:
n.dtype()

NameError: name 'n' is not defined

In [49]:
np.dtype()

TypeError: dtype() missing required argument 'dtype' (pos 1)

In [50]:
n=np.array(ls)

In [51]:
n

array([0, 2, 4, 6, 8])

In [54]:
n.dtype

dtype('int32')

In [63]:
ls.append(5)

In [64]:
ls


[0, 2, 4, 6, 8, 5]

In [65]:
mn=np.array(ls)

In [66]:
n.reshape(2,3)

array([[0, 2, 4],
       [6, 8, 5]])

In [72]:
mn=np.array(ls)

In [77]:
ls=([[1,2,5,6],[1,6,5,9],[8,9,6,4],[6,5,9,4]])

In [78]:
ls


[[1, 2, 5, 6], [1, 6, 5, 9], [8, 9, 6, 4], [6, 5, 9, 4]]

In [79]:
mn=np.array(ls)

In [80]:
mn.shape


(4, 4)

In [81]:
mn[0:2,1:3]

array([[2, 5],
       [6, 5]])

In [82]:
ls1=[1,2,3,4,5,6,7,8,9]

In [83]:
ls1>5

TypeError: '>' not supported between instances of 'list' and 'int'

In [84]:
n

array([0, 2, 4, 6, 8, 5])

In [85]:
n>5

array([False, False, False,  True,  True, False])

In [94]:
n.all

<function ndarray.all>

In [97]:
n+10

array([10, 12, 14, 16, 18, 15])

In [98]:
n*2

array([ 0,  4,  8, 12, 16, 10])

In [99]:
n*n

array([ 0,  4, 16, 36, 64, 25])

In [102]:
1/n

C:\Users\Yogesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.2       ])

In [103]:
n/1


array([0., 2., 4., 6., 8., 5.])

In [104]:
n.sum()

25